config {
  type: "view",
  database: "dudledood-sql-project-1"
  schema: "dataform",
  tags: ["daily"],
  bigquery: {
    partitionBy: "date(created_at)"
  },
  description: "Combine both questions and answers into a single posts_all table",
  assertions: {
    uniqueKey: ["post_id"]
  }
}

select
  post_id,
  created_at,
  type,
  title,
  body,
  owner_user_id,
  parent_id
from
  `transcript_dataset.cleaned_transcript1`

